name: WolnyNokaut
version: '${project.version}'
main: pl.wolny.wolnynokaut.WolnyNokaut
api-version: 1.18
authors: [ WcaleNieWolny ]
description: Knockaut - implementation without any packet bs
depend: [ProtocolLib]
commands:
  harakiri:
    description: Accepts death.
    aliases:
      - zginodrazu
      - akceptujsmierc