name: WolnyNokaut
version: '${project.version}'
main: pl.wolny.wolnynokaut.WolnyNokaut
api-version: 1.17
authors: [ WcaleNieWolny ]
description: Knockaut - implementation without any packet bs
depend: [ ProtocolLib ]
softdepend: [ WorldGuard ]
commands:
  harakiri:
    description: Accepts death.
    aliases:
      - zginodrazu
      - akceptujsmierc
  pickup:
    description: pickup player
    aliases:
      - podniesgracza
  ground:
    description: place player on the ground
    aliases:
      - rzucgracza