name: TobiaszNokaut
version: ${project.version}
main: pl.wolny.junglenokaut.JungleNokaut
api-version: 1.16
author: WcaleNieWolny
description: Nokaut pisany na zlecenie.
softdepend:
  - Matrix
commands:
  akceptujsmierc:
    description: Akceptuje śmierć.
    aliases:
      - zginodrazu
      - harakiri
  podniesgracza:
    description: Podnosi gracza.
  rzucgracza:
    aliases:
      - zrzucgracza
    description: Rzuca gracza.
permissions:
  tobiasznokaut.updateinfo:
    description: shows information about the update
    default: op
